### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by all3xfx** [iamtodor/angel.co-companies-list-scraping#2]
When trying:
python3 parse.py -q='computer vision'

I have this error:

Traceback (most recent call last):
  File "parse.py", line 116, in <module>
    start()
  File "parse.py", line 108, in start
    for idx, comps in enumerate(companies):
  File "parse.py", line 61, in get_next_pages
    'filter_data[markets][]':search_query}, headers=headers).json()
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(angelscrap) iMac:angel.co-companies-list-scraping alex$ python3 parse.py -q=‘visao’
Traceback (most recent call last):
  File "parse.py", line 116, in <module>
    start()
  File "parse.py", line 108, in start
    for idx, comps in enumerate(companies):
  File "parse.py", line 61, in get_next_pages
    'filter_data[markets][]':search_query}, headers=headers).json()
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(angelscrap) iMac:angel.co-companies-list-scraping alex$ python3 parse.py
Traceback (most recent call last):
  File "parse.py", line 116, in <module>
    start()
  File "parse.py", line 108, in start
    for idx, comps in enumerate(companies):
  File "parse.py", line 61, in get_next_pages
    'filter_data[markets][]':search_query}, headers=headers).json()
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/alex/anaconda/envs/angelscrap/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by all3xfx** [comment]
I couldn't correct this issue. Would you help me? Thanks.

**Comment by Rajput245** [comment]
i am getting the same error.

**Comment by iamtodor** [comment]
I have checked it: the response code is 403 and the reason is `Forbidden`. I think https://angel.co/ have changed something or even closed this way to parse the site.

**Comment by tszjqgs** [comment]
same error I got , any one can help and resolve this ?
